/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dit.panels;

import dit.DEIDGUI;
import dit.DeidData;
import dit.FileUtils;
import java.awt.Window;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author christianprescott & angelo
 */
public class CompletePanel extends javax.swing.JPanel implements WizardPanel {

    /**
     * Creates new form CompletePanel
     */
    public CompletePanel() {
        initComponents();
        DEIDGUI.title = "Complete";
        DEIDGUI.helpButton.setEnabled(true);
        DEIDGUI.helpButton.setVisible(false);
        DEIDGUI.continueButton.setEnabled(false);
        DEIDGUI.cancelButton.setEnabled(false);
        DEIDGUI.backButton.setEnabled(false);
   
        if (!DeidData.tarfilesavedpath.equals("")) {
            int lg = DeidData.tarfilesavedpath.length();
            
            if (lg < 70) {
                jLabel2.setText("<html><p>Your data has been saved to: </p><div>" + DeidData.tarfilesavedpath + "</div>");
               
            } else {
                String str1 = DeidData.tarfilesavedpath.substring(0, 70);
                String str2 = DeidData.tarfilesavedpath.substring(71);
                System.out.println(str1);
                System.out.println(str2);
                jLabel2.setText("<html><p>Your data have been saved to: </p><p>" + str1 + "</p><p>" + str2 + "</p>");
            }
        }    
        if(!DeidData.mapfilesavedpath.equals("")) {
            int lgm = DeidData.mapfilesavedpath.length();
            if (lgm < 70) {
                jLabel2.setText(jLabel2.getText() + "<p>Your ID mapping data has been saved to: </p><div>" + DeidData.mapfilesavedpath + "</div>");                   
            } else {
                String str1 = DeidData.mapfilesavedpath.substring(0, 70);
                String str2 = DeidData.mapfilesavedpath.substring(71);
                System.out.println(str1);
                System.out.println(str2);
                jLabel2.setText(jLabel2.getText() + "<p>Your data have been saved to: </p><p>" + str1 + "</p><p>" + str2 + "</p>");
            }
             
            //jLabel2.setText(jLabel2.getText() + "</html>");
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("You cannot move back to a previous step because the temporary files have been cleaned up.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(144, 144, 144)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO: Delete files in the temporary output folder
            FileUtils.deleteRecursive(new File(DeidData.outputPath));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DEIDGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        DEIDGUI.log("Temp files deleted");
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public WizardPanel getNextPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public WizardPanel getPreviousPanel() {
        return new TransferPanel();
    }
}
