package dit.panels;

import dit.*;
import dit.DEIDGUI;
import java.awt.Component;
import java.awt.Container;
import java.io.*;
import java.io.File;
import java.lang.String;
import java.util.Enumeration;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.*;

/**
 *
 * @author christianprescott
 */
public class LoadImagesPanel extends JPanel implements WizardPanel {
    
    public final static DefaultTreeModel model = new DefaultTreeModel(new DefaultMutableTreeNode("")) ;
    
    /**
     * Creates new form LoadImagesPanel
     */
    public LoadImagesPanel() {
        initComponents();
        DEIDGUI.title = "Load Images";
        
        lblImages.setText(DeidData.imageHandler.getInputFiles().size()+" images loaded");
        cbxDoDeface.setSelected(!DeidData.doDeface);
        
        btnRemovedAll.setVisible(false);
                
        jTree.setModel(model);
        FileTreeCellRenderer renderer = new FileTreeCellRenderer();
        renderer.setLeafIcon(UIManager.getIcon("FileView.fileIcon")); // used for leaf nodes
        jTree.setCellRenderer(renderer);
        jTree.setRootVisible(false);    
        jTree.addTreeSelectionListener(new TreeSelectionListener() { //It's not the real num of selected files
            @Override
            public void valueChanged(TreeSelectionEvent e) {               
                int arr[] = jTree.getSelectionRows();
                jLabel2.setText(arr.length+" line(s) selected");
            }
        });
        
        DEIDGUI.log("LoadImagesPanel initialized");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddFiles = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        btnSelectAll = new javax.swing.JButton();
        btnRemovedAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblImages = new javax.swing.JLabel();
        btnAddDir = new javax.swing.JButton();
        cbxDoDeface = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        jLabel1.setText("<html><p>Select images or directories of images to de-identify. Images may be in DICOM, Analyze, or NIfTI format. DICOM and Analyze files will be converted to NIfTI.</p><p>&nbsp;</p></html>");

        btnAddFiles.setText("Add Images From 1 Directory");
        btnAddFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilesActionPerformed(evt);
            }
        });

        jButtonRemove.setText("Remove Selected");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        btnSelectAll.setText("Select All");
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnRemovedAll.setText("Clear All");
        btnRemovedAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovedAllActionPerformed(evt);
            }
        });

        jLabel2.setText("No line is selected.");

        lblImages.setText("0 images loaded");

        btnAddDir.setText("Add Images From Multiple Directories");
        btnAddDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirActionPerformed(evt);
            }
        });

        cbxDoDeface.setForeground(new java.awt.Color(255, 0, 0));
        cbxDoDeface.setText("The images have already been skull-stripped.");
        cbxDoDeface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDoDefaceActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTree);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .add(134, 134, 134))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(btnAddFiles)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnAddDir))
                            .add(layout.createSequentialGroup()
                                .add(cbxDoDeface, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(btnSelectAll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonRemove))
                            .add(lblImages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(98, 98, 98)
                                .add(btnRemovedAll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAddFiles)
                    .add(btnRemovedAll)
                    .add(btnAddDir))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(lblImages))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbxDoDeface)
                    .add(jButtonRemove)
                    .add(btnSelectAll))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //private Vector<File> displayedFiles = new Vector<File>();
    private void btnAddFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilesActionPerformed
        final javax.swing.JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        LoadImage(fc);   
    }//GEN-LAST:event_btnAddFilesActionPerformed
    
    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
       
        DefaultMutableTreeNode node;
        TreePath[] paths = jTree.getSelectionPaths();
        int num = 0;
        for (int i = 0; i < paths.length; i++) {
          node = (DefaultMutableTreeNode) (paths[i].getLastPathComponent()); 
          removeRecursive(node, num);
        }
        //printAllImages();
        reVaildateTreeModel();
        DEIDGUI.log("Removed " + num + " input images");
        jLabel2.setText("No line is selected.");
        lblImages.setText(DeidData.imageHandler.getInputFilesSize()+" images loaded");
        
    }//GEN-LAST:event_jButtonRemoveActionPerformed
    
    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        // TODO add your handling code here:
        TreeNode root = (TreeNode) jTree.getModel().getRoot();
        selectAll(jTree, new TreePath(root));
        jLabel2.setText(DeidData.imageHandler.getInputFiles().size()+" line(s) selected."); 
    }//GEN-LAST:event_btnSelectAllActionPerformed
    
    private void btnRemovedAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovedAllActionPerformed
        // TODO add your handling code here:
        TreeNode root = (TreeNode) jTree.getModel().getRoot();
        selectAll(jTree, new TreePath(root));
        DefaultMutableTreeNode node;
        TreePath[] paths = jTree.getSelectionPaths();
        int num = 0;
        for (int i = 0; i < paths.length; i++) {
          
          node = (DefaultMutableTreeNode) (paths[i].getLastPathComponent());         
          removeRecursive(node, num);
        }
        //printAllImages();
        reVaildateTreeModel();
        jLabel2.setText("No line is selected.");
    }//GEN-LAST:event_btnRemovedAllActionPerformed
    
    private void btnAddDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirActionPerformed
        // TODO add your handling code here:
        final javax.swing.JFileChooser fc = new JFileChooser(){
            public void approveSelection(){
                if(getSelectedFile().isFile())
                    return;
                else
                    super.approveSelection();
            }
        };
        hideTextfield(fc.getComponents());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        LoadImage(fc);
    }//GEN-LAST:event_btnAddDirActionPerformed

    private void cbxDoDefaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDoDefaceActionPerformed
        DeidData.doDeface=!cbxDoDeface.isSelected();
    }//GEN-LAST:event_cbxDoDefaceActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDir;
    private javax.swing.JButton btnAddFiles;
    private javax.swing.JButton btnRemovedAll;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JCheckBox cbxDoDeface;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblImages;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public WizardPanel getNextPanel() {
        final WizardPanel nextPanel;
        
        /*
        DeidData.niftiFiles.clear();
        // Determine if conversions of the selected images are necessary
        HashSet<File> dicomDirs = new HashSet<File>(),
                analyzePairs = new HashSet<File>();
        Iterator<File> imageIt = FileUtils.getFileListRecursively(
                DeidData.inputFiles, 1).iterator();
        while (imageIt.hasNext()) {
            File curImage = imageIt.next();
            String extension = FileUtils.getExtension(curImage);
            if (extension.equals(FileUtils.Extensions.dicom)) {
                // Use the parent directory of the file because dcm2nii will do
                // so anyway. Specifying each file is redundant.
                dicomDirs.add(curImage.getParentFile());
            } else   // bet can handle hdr/img/nii files
                     //Conversion will never be used.
            {
                DeidData.niftiFiles.add(curImage);
            }
        }
        */
            nextPanel = new LoadDemoPanel();
       
        return nextPanel;
    }
    
    @Override
    public WizardPanel getPreviousPanel() {
        return new UserPanel();
    }
    
    public final DefaultTreeModel getModel() {
        return model;
    }
    
    //this function make file selection textfield and label do not display
    private void hideTextfield(Component[] jc){
        for(int i=0;i<jc.length;i++)
        {
            Component c=jc[i];
            if(c instanceof JTextField)
            {
                 c.setVisible(false);
            }
            
            if(c instanceof JLabel)
            {
                String text=((JLabel)c).getText();
                if(text.startsWith("Selection:"))
                  c.getParent().setVisible(false);
            }
            if(c instanceof Container)
                hideTextfield(((Container)c).getComponents());
        }
    }
    
    private void LoadImage(JFileChooser fc)
    {
        fc.setMultiSelectionEnabled(true);
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new ImageFilter());
        String dirrec;
        File filename = new File("/tmp/imagepath.txt");
        try{
            FileReader fr = new FileReader(filename);
            BufferedReader br = new BufferedReader(fr);
            dirrec = br.readLine();
            if (dirrec!= null)
            {
                fc.setCurrentDirectory(new File(dirrec));
            }
            
        }catch(IOException e)
        {
            fc.setCurrentDirectory(null);
        }
        
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] selectedFiles = fc.getSelectedFiles();
            //angelo added
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
            for (File file : selectedFiles) {
                addRecusive(file, root);             
            }
            model.reload();
            
            String dir = fc.getSelectedFile().getParent();
            if (!filename.exists()){
                //try{
                    filename.mkdirs();
                //}
                //catch (IOException e) {
                //    DEIDGUI.log("Fail to create file!" );
                //}
                
            }
            try
            {
                RandomAccessFile  pathfile = new RandomAccessFile (filename,"rw");
                pathfile.writeBytes(dir);
            }catch(IOException e)
            {
                DEIDGUI.log("No Parent Directory Found!" );
            }
            DEIDGUI.log("Added " + DeidData.imageHandler.getInputFilesSize() + " input images");
            
            LoggerWrapper.myLogger.log(Level.INFO, "Added {0} input images", DeidData.imageHandler.getInputFilesSize());
            LoggerWrapper.myLogger.log(Level.INFO, "Images are {0} to be skull stripped", DeidData.doDeface ? "" : "not");
            lblImages.setText(DeidData.imageHandler.getInputFilesSize() +" image(s) loaded.");
        }
    }
   
    private void selectAll(JTree tree, TreePath parent) {
        TreeNode node = (TreeNode) parent.getLastPathComponent();
        if (node.getChildCount() >= 0) {
          for (Enumeration e = node.children(); e.hasMoreElements();) {
            TreeNode n = (TreeNode) e.nextElement();
            TreePath path = parent.pathByAddingChild(n);
            selectAll(tree, path);
          }
        }
        tree.expandPath(parent);
        tree.setSelectionInterval(0, tree.getRowCount());
        // tree.collapsePath(parent);
  }
    
    private void removeRecursive(DefaultMutableTreeNode node, int num) {
        File file = new File(node.getUserObject().toString());
        
        if (file.isDirectory()){
            while (node.getChildCount() > 0){
                removeRecursive((DefaultMutableTreeNode)node.getFirstChild(), num); 
            }
            try{
                model.removeNodeFromParent(node);
            } catch (IllegalArgumentException e){}
        }
        else {
            if (isImageFile(file)){
                DeidData.imageHandler.remove((NIHImage)node.getUserObject());
                num++;
            }
            try{
                model.removeNodeFromParent(node);
            } catch (IllegalArgumentException e){}
        }    
    }
     
    /**
     * make sure no empty folder on leaf node 
     */
    private void reVaildateTreeModel(){ 
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        Enumeration e = root.depthFirstEnumeration();
        while (e.hasMoreElements()) {
            DefaultMutableTreeNode nextnode = (DefaultMutableTreeNode) e.nextElement();
            if (nextnode.isLeaf()){
                File file = new File(nextnode.getUserObject().toString());
                if ( file.isDirectory()&& nextnode.getParent() != null){
                        model.removeNodeFromParent(nextnode);
                }
            }
        }
        model.reload();
    }
    
    private boolean isImageFile(File file){
        return (file.getName().endsWith(".nii")||file.getName().endsWith(".nii.gz")||file.getName().endsWith(".dcm")||file.getName().endsWith(".img")||file.getName().endsWith(".hdr")) ;
    
    }
    
    protected void addRecusive(File file, DefaultMutableTreeNode parent) {
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(file);
        if (file.isDirectory() && file.listFiles().length > 0){
            model.insertNodeInto(newNode, parent, parent.getChildCount());
            File[] files = file.listFiles();
            for (File ff : files){
                addRecusive(ff, newNode);
            }
        }
        else {
            if ( isImageFile(file)  && DeidData.addInputFile(file)){

                newNode = new DefaultMutableTreeNode(DeidData.imageHandler.getInputFiles().get(DeidData.imageHandler.getInputFilesSize()-1));
                model.insertNodeInto(newNode, parent, parent.getChildCount());
                
                //display newNode
                TreeNode[] nodes = model.getPathToRoot(newNode);
                TreePath path = new TreePath(nodes);
                jTree.scrollPathToVisible(path);   
            }
        }
    }
    
    public class FileTreeCellRenderer extends DefaultTreeCellRenderer {

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            if (value instanceof DefaultMutableTreeNode) {
                value = ((DefaultMutableTreeNode)value).getUserObject();
                
                if (value instanceof File && ((File) value).isDirectory()) {
                        value = ((File) value).getName();
                }
                if (value instanceof NIHImage) {
                    String fullname = ((NIHImage) value).getImageName();
                    String imageName;
                    try {
                        imageName = fullname.substring(fullname.lastIndexOf(File.separator)+1);
                        value = imageName;
                    }   catch(StringIndexOutOfBoundsException e){
                        value = fullname;
                    }
                }
            }
            return super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
        }
    }
    
}
