package dit.panels;

import dit.DEIDGUI;
import dit.*;
import java.awt.Component;
import java.awt.Container;
import java.io.File;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import java.util.Vector;
import java.util.List;
import java.lang.String;
import java.util.logging.Level;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author christianprescott
 */
public class LoadImagesPanel extends JPanel implements WizardPanel {
    
    /**
     * Creates new form LoadImagesPanel
     */
    public LoadImagesPanel() {
        initComponents();
        DEIDGUI.title = "Load Images";
        
        
        lblImages.setText(DeidData.imageHandler.getInputFiles().size()+" images loaded");
        jListImages.setListData(DeidData.imageHandler.getInputFiles());
        cbxDoDeface.setSelected(!DeidData.doDeface);
        
        btnRemovedAll.setVisible(false);
        
        jListImages.addListSelectionListener(new ListSelectionListener(){
            @Override  public void valueChanged(ListSelectionEvent e){
                jLabel2.setText(jListImages.getSelectedValues().length+" line(s) selected");
                
            }
        }
                
                );
        DEIDGUI.log("LoadImagesPanel initialized");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddFiles = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListImages = new javax.swing.JList();
        jButtonRemove = new javax.swing.JButton();
        btnSelectAll = new javax.swing.JButton();
        btnRemovedAll = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblImages = new javax.swing.JLabel();
        btnAddDir = new javax.swing.JButton();
        cbxDoDeface = new javax.swing.JCheckBox();

        jLabel1.setText("<html><p>Select images or directories of images to de-identify. Images may be in DICOM, Analyze, or NIfTI format. DICOM and Analyze files will be converted to NIfTI.</p><p>&nbsp;</p></html>");

        btnAddFiles.setText("Add Images From 1 Directory");
        btnAddFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFilesActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListImages);

        jButtonRemove.setText("Remove Selected");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        btnSelectAll.setText("Select All");
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnRemovedAll.setText("Clear All");
        btnRemovedAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovedAllActionPerformed(evt);
            }
        });

        jLabel2.setText("No line is selected.");

        lblImages.setText("0 images loaded");

        btnAddDir.setText("Add Images From Multiple Directories");
        btnAddDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDirActionPerformed(evt);
            }
        });

        cbxDoDeface.setForeground(new java.awt.Color(255, 0, 0));
        cbxDoDeface.setText("The images have already been skull-stripped.");
        cbxDoDeface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDoDefaceActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .add(134, 134, 134))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(btnAddFiles)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnAddDir)))
                        .add(0, 0, 0)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblImages, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(98, 98, 98)
                                .add(btnRemovedAll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(cbxDoDeface, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(77, 77, 77)
                        .add(btnSelectAll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonRemove)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAddFiles)
                    .add(btnRemovedAll)
                    .add(btnAddDir))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(lblImages))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbxDoDeface)
                    .add(jButtonRemove)
                    .add(btnSelectAll))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void ReadAllFile(Vector<File> list, String filePath) {
        File f = null;
        f = new File(filePath);
        File[] files = f.listFiles(); // get all files
        for (File file : files) {
            if(file.isDirectory()) {
                
                ReadAllFile(list, file.getAbsolutePath());
            } else {
                if (file.getName().endsWith(".nii")||file.getName().endsWith(".nii.gz")||file.getName().endsWith(".dcm")||file.getName().endsWith(".img")||file.getName().endsWith(".hdr"))
                    list.add(file);
            }
        }
        //for(int i=0; i< list.size(); i++) {
        //  System.out.println(list.get(i).getAbsolutePath());
        //}
        
    }
    //private Vector<File> displayedFiles = new Vector<File>();
    private void btnAddFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFilesActionPerformed
        final javax.swing.JFileChooser fc = new JFileChooser();
         fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        LoadImage(fc);   
        
    }//GEN-LAST:event_btnAddFilesActionPerformed
    
    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        List selection = jListImages.getSelectedValuesList();
        DeidData.imageHandler.removeAll(selection);
        jListImages.setListData(DeidData.imageHandler.getInputFiles());
        DEIDGUI.log("Removed " + selection.size() + " input images");
        jLabel2.setText("No line is selected.");
        lblImages.setText(DeidData.imageHandler.getInputFilesSize()+" images loaded");
    }//GEN-LAST:event_jButtonRemoveActionPerformed
    
    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        // TODO add your handling code here:
        int ind[];
        ind = new int[DeidData.imageHandler.getInputFiles().size()];
        for(int i = 0; i< DeidData.imageHandler.getInputFiles().size();i++ )
        {
            ind[i] = i;            
        }
        jListImages.setSelectedIndices(ind);
        jLabel2.setText(DeidData.imageHandler.getInputFiles().size()+" line(s) selected.");
    }//GEN-LAST:event_btnSelectAllActionPerformed
    
    private void btnRemovedAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovedAllActionPerformed
        // TODO add your handling code here:
        jListImages.clearSelection();
        jLabel2.setText("No line is selected.");
    }//GEN-LAST:event_btnRemovedAllActionPerformed
    
    private void btnAddDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDirActionPerformed
        // TODO add your handling code here:
        final javax.swing.JFileChooser fc = new JFileChooser(){
            public void approveSelection(){
                if(getSelectedFile().isFile())
                    return;
                else
                    super.approveSelection();
            }
        };
        hideTextfield(fc.getComponents());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        LoadImage(fc);
    }//GEN-LAST:event_btnAddDirActionPerformed

    private void cbxDoDefaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDoDefaceActionPerformed
        DeidData.doDeface=!cbxDoDeface.isSelected();
    }//GEN-LAST:event_cbxDoDefaceActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDir;
    private javax.swing.JButton btnAddFiles;
    private javax.swing.JButton btnRemovedAll;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JCheckBox cbxDoDeface;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jListImages;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImages;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public WizardPanel getNextPanel() {
        final WizardPanel nextPanel;
        
        /*
        DeidData.niftiFiles.clear();
        // Determine if conversions of the selected images are necessary
        HashSet<File> dicomDirs = new HashSet<File>(),
                analyzePairs = new HashSet<File>();
        Iterator<File> imageIt = FileUtils.getFileListRecursively(
                DeidData.inputFiles, 1).iterator();
        while (imageIt.hasNext()) {
            File curImage = imageIt.next();
            String extension = FileUtils.getExtension(curImage);
            if (extension.equals(FileUtils.Extensions.dicom)) {
                // Use the parent directory of the file because dcm2nii will do
                // so anyway. Specifying each file is redundant.
                dicomDirs.add(curImage.getParentFile());
            } else   // bet can handle hdr/img/nii files
                     //Conversion will never be used.
            {
                DeidData.niftiFiles.add(curImage);
            }
        }
        */
            nextPanel = new LoadDemoPanel();
       
        return nextPanel;
    }
    
    @Override
    public WizardPanel getPreviousPanel() {
        return new UserPanel();
    }
    
    
    //this function make file selection textfield and label do not display
    private void hideTextfield(Component[] jc){
        for(int i=0;i<jc.length;i++)
        {
            Component c=jc[i];
            if(c instanceof JTextField)
            {
                 c.setVisible(false);
            }
            
            if(c instanceof JLabel)
            {
                String text=((JLabel)c).getText();
                if(text.startsWith("Selection:"))
                  c.getParent().setVisible(false);
            }
            if(c instanceof Container)
                hideTextfield(((Container)c).getComponents());
        }
    }
    
    private void LoadImage(JFileChooser fc)
    {
        
        fc.setMultiSelectionEnabled(true);
       
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new ImageFilter());
        String dirrec;
        File filename = new File("/tmp/imagepath.txt");
        try{
            FileReader fr = new FileReader(filename);
            BufferedReader br = new BufferedReader(fr);
            dirrec = br.readLine();
    ;
            if (dirrec!= null)
            {
                fc.setCurrentDirectory(new File(dirrec));
            }
            
        }catch(IOException e)
        {
            fc.setCurrentDirectory(null);
        }
        
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] selectedFiles = fc.getSelectedFiles();
            //angelo added
            for (int idx = 0; idx < selectedFiles.length; idx ++)
            {
                if(selectedFiles[idx].isDirectory())
                {
                    Vector<File> imgfiles = new Vector<File>();
                    ReadAllFile(imgfiles, selectedFiles[idx].getAbsolutePath());
                    DeidData.parentPath = selectedFiles[idx].getParentFile().getAbsolutePath();
                    DeidData.addInputFile(imgfiles);
                }
                else{
                    DeidData.addInputFile(selectedFiles[idx]);
                   // DeidData.parentPath="none";
                }
            }
            jListImages.setListData(DeidData.imageHandler.getInputFiles());
            
            String dir = fc.getSelectedFile().getParent();
            
            
            if (!filename.exists()){
                //try{
                    filename.mkdirs();
                //}
                //catch (IOException e) {
                //    DEIDGUI.log("Fail to create file!" );
                //}
                
            }
            try
            {
                
                RandomAccessFile  pathfile = new RandomAccessFile (filename,"rw");
                pathfile.writeBytes(dir);
            }catch(IOException e)
            {
                DEIDGUI.log("No Parent Directory Found!" );
            }
            DEIDGUI.log("Added " + DeidData.imageHandler.getInputFilesSize() + " input images");
            
            LoggerWrapper.myLogger.log(Level.INFO, "Added {0} input images", DeidData.imageHandler.getInputFilesSize());
            LoggerWrapper.myLogger.log(Level.INFO, "Images are {0} to be skull stripped", DeidData.doDeface ? "" : "not");
            lblImages.setText(DeidData.imageHandler.getInputFilesSize() +" image(s) loaded.");
        }
    }
}
