/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dit.panels;

import dit.DEIDGUI;
import dit.DeidData;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.Vector;


/**
 *
 * @author christianprescott
 */
public class UserPanel extends javax.swing.JPanel implements WizardPanel{

    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
        DEIDGUI.title = "User Information";
        DEIDGUI.backButton.setEnabled(true);
        DEIDGUI.helpButton.setEnabled(true);
        jTextFieldName.setText(DeidData.UserFullName);
        jTextFieldInstitution.setText(DeidData.UserInstitution);
        ValidateFields();
        DeidData.errorlog = new Vector();
        
        ActionListener al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {if(ValidateFields()){DEIDGUI.advance();}}
        };
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {ValidateFields();}
            @Override
            public void removeUpdate(DocumentEvent de) {ValidateFields();}
            @Override
            public void changedUpdate(DocumentEvent de) {ValidateFields();}
        };
        jTextFieldName.getDocument().addDocumentListener(dl);
        jTextFieldName.addActionListener(al);
        jTextFieldInstitution.getDocument().addDocumentListener(dl);
        jTextFieldInstitution.addActionListener(al);
        // TODO: Save name and instituion, maybe in tmp folder?
    }

    private boolean ValidateFields(){
        if(jTextFieldName.getText().length() > 0 &&
                jTextFieldInstitution.getText().length() > 0){
            DEIDGUI.continueButton.setEnabled(true);
            return true;
        } else {
            DEIDGUI.continueButton.setEnabled(false);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JTextField();
        jTextFieldInstitution = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelInstitution = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextFieldName.setMaximumSize(new java.awt.Dimension(200, 2147483647));

        jTextFieldInstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstitutionActionPerformed(evt);
            }
        });

        jLabelName.setText("Full Name");

        jLabelInstitution.setText("Institution");

        jLabel1.setText("<html><p>&nbsp</p><p>Enter your name and institution.  Clicking the 'Continue' button will take you to the next 'load images' step.</p><p>&nbsp</p></html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelInstitution)
                            .add(jLabelName))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jTextFieldInstitution))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(65, 65, 65)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelInstitution)
                    .add(jTextFieldInstitution, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstitutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstitutionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInstitution;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField jTextFieldInstitution;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    @Override
    public WizardPanel getNextPanel() {
        DeidData.UserFullName = jTextFieldName.getText().trim();
        DeidData.UserInstitution = jTextFieldInstitution.getText().trim();
               
        if(DeidData.UserFullName.isEmpty() || DeidData.UserInstitution.isEmpty()){
            DEIDGUI.log("One or more user data fields are empty", DEIDGUI.LOG_LEVEL.ERROR);
            throw new IllegalStateException("One or more user data fields are empty");
        }
        
        return new LoadImagesPanel();
    }

    @Override
    public WizardPanel getPreviousPanel() {
        //throw new UnsupportedOperationException("Not supported yet.");
      
        return new WelcomePanel();
    }
}
